Create API for Report Flow
hyperjumptech/symon pull request #151
Opened 2021-04-23 08:06 UTC by armedi

2021-04-29 03:22 UTC, kevinhermawan approved these changes

2021-04-29 07:13 UTC, nicnocquee requested changes

2021-04-29 07:13 UTC, nicnocquee commented on src/server/prisma/schema.prisma
> +  report report @relation(fields: [reportId], references: [id])
I think we should add `monikaId` field here so that it's easier to query. For example, we might want to display a response time graph from a certain location.

2021-04-29 07:23 UTC, armedi commented on src/server/prisma/schema.prisma
> +  report report @relation(fields: [reportId], references: [id])
@nicnocquee 

monikaId field exists in the `report` table, the relationship is as the following image

<img width="543" alt="Screen Shot 2021-04-29 at 14 17 11" src="https://user-images.githubusercontent.com/22452017/116514721-9aa6ab00-a8f5-11eb-8edb-baf47f0fc1b4.png">

For querying response time for specific monika instance we may use query like:

```sql
SELECT RD.request_url, RD.response_time from monika M JOIN report R ON M.id = R.monika_id  JOIN reportData RD ON R.id = RD.report_id where M.id = 1;
```

2021-04-29 07:29 UTC, ilmiawan approved these changes

2021-04-29 07:52 UTC, sapiderman approved these changes

2021-04-29 08:48 UTC, armedi commented on src/server/prisma/schema.prisma
> +  report report @relation(fields: [reportId], references: [id])
updated

2021-04-30 06:28 UTC, nicnocquee approved these changes

2021-04-30 06:28 UTC, merged