feat: login page
hyperjumptech/symon pull request #183
Opened 2021-05-17 03:02 UTC by raosan

# Symon Pull Request (PR)

### what issue does this pr address

implementing issue no #177  which adds feature login page

### how did you implement / how did you fix it

1. create rememberMe function to save state in localStorage
2. create 2 API endpoints to check is there already user and create first user if no user in DB
3. wire the API to FE

### how **DID** you test

1. npm start
2. check localhost:4000/login
3. if you already seed the DB, login with the seeded user credential (email:admin@symon.org | password:right password). You can check that the access token is stored on localStorage and you will be redirected to home page.
4. open localhost:4000/login again and you will not redirected to home page because "remember me" check is uncheck. Now repeat above step to login again, and when you visit login page again, you will be auto redirected to home page
5. Now test for case of no pre seed user. Delete the DB, then visit login page again and you will see "crate new user" form. Fill the form and the user is created and you will be automatically logged in.

### any other info/context

On a second thought, the seed user is a user zero which can be treated as "already created user". So the one case to display create user form is when there is no user at all in DB. If the seeded user is not treated as user zero, than we cannot log in with that user in the first time, so there is no point in creating the seed

2021-05-17 08:34 UTC, dennypradipta commented
![image](https://user-images.githubusercontent.com/16670475/118458792-49841d00-b725-11eb-8a43-feb30d2da7f9.png)

Could you please remove the Remember Me in create form?

2021-05-17 08:39 UTC, nicnocquee requested changes

2021-05-17 08:39 UTC, nicnocquee commented on src/server/services/auth/index.ts
>  router.post("/v1/auth", login);
better to use validate here too to be consistent.

2021-05-17 08:39 UTC, nicnocquee commented on src/client/pages/Login/Login.tsx
> +  }, []);
maybe add the history in the dependency here to remove the eslint-disable

2021-05-17 09:20 UTC, raosan commented
> ![image](https://user-images.githubusercontent.com/16670475/118458792-49841d00-b725-11eb-8a43-feb30d2da7f9.png)
> 
> Could you please remove the Remember Me in create new user form?

fixed. please recheck...

2021-05-18 08:07 UTC, nicnocquee approved these changes

2021-05-18 08:27 UTC, dennypradipta approved these changes

2021-05-18 08:27 UTC, merged