Feat: Add Probe Requests Page
hyperjumptech/symon pull request #189
Opened 2021-05-24 13:25 UTC by haricnugraha

# Symon Pull Request (PR)

### What issue does this pr address

1. Fixes issue #173
- [x] User should be able to see the list of probing events
- [x] The list is sorted by time, newest first.
- [x] The list is paginated. Shows 30 events at a time.
- [x] When user clicks Load More button, shows the next 30 events.

### How did you implement / how did you fix it

1. Add seed data
2. Add query helper to translate query param to Prisma query
3. Add report request list endpoint
4. Fetch data from backend

### How **DID** you test

1. run `npm run seed`
2. run `npm start`
3. open localhost:4000/login and login
4. open localhost:4000/hyperjump/1/sample-probe/requests
5. run `npm test`

2021-05-24 21:29 UTC, nicnocquee requested changes

2021-05-24 21:29 UTC, nicnocquee commented on src/server/services/report-requests/controller.ts
> +      searchableFileds: ["probeName", "requestUrl"],
typo `searchableFields` ?

2021-05-24 21:29 UTC, nicnocquee commented on src/server/internal/query-helper.ts
> +  searchableFileds?: Array<string>,
typo `searchableFields` ?

2021-05-24 21:29 UTC, nicnocquee commented on src/server/internal/query-helper.ts
> +  searchableFileds?: Array<string>;
typo `searchableFields` ?

2021-05-25 07:19 UTC, raosan approved these changes

2021-05-25 07:38 UTC, armedi approved these changes

2021-05-25 08:02 UTC, nicnocquee approved these changes

2021-05-25 08:07 UTC, merged