Copywriting improvement when probe does not exist
hyperjumptech/symon pull request #250
Opened 2021-06-24 10:03 UTC by samsunoor

# Symon Pull Request (PR)

### What issue does this pr address
1. This PR resolves #242 which improves copywriting when current user does not have any probes configured.
2. Telling user does not have probes and add link to [monika quick start guide](https://monika.hyperjump.tech/quick-start)

### How did you implement
1. improve default home page on `src/client/pages/Home/Home.tsx`

### How to test
1. Clear development data and run project
```
# remove development db
$ rm src/server/prisma/dev.db

# run db migration
$ npx prisma migrate dev --preview-feature
$ npx prisma generate
$ npm run start
```
3. Check `localhost:4000`
4. Login default user
5. Should see the screen as below
![image](https://user-images.githubusercontent.com/9563873/123244420-1eec6780-d50e-11eb-8c41-991e9d4e174a.png)

2021-06-24 13:05 UTC, raosan approved these changes

2021-06-24 16:51 UTC, nicnocquee requested changes

2021-06-24 16:51 UTC, nicnocquee commented on src/client/pages/Home/Home.tsx
> +      <p style={{ marginTop: "1rem" }}>
use `className="mt-8"` since we're using tailwind.

2021-06-24 16:51 UTC, nicnocquee commented on src/client/pages/Home/Home.tsx
> +        <a href="https://monika.hyperjump.tech/quick-start">
use `className="underline"` instead of `<u>`

2021-06-25 06:37 UTC, kevinhermawan commented on src/client/pages/Home/Home.tsx
> +      <strong>You don&apos;t have any probes yet.</strong>
Why use `&apos;` instead of `'` symbol?

2021-06-25 06:39 UTC, nicnocquee commented on src/client/pages/Home/Home.tsx
> +      <strong>You don&apos;t have any probes yet.</strong>
i think eslint or something warns to escape some symbols.

2021-06-25 06:41 UTC, samsunoor commented on src/client/pages/Home/Home.tsx
> +      <strong>You don&apos;t have any probes yet.</strong>
true, I use it since the eslint would return error about not escaped symbol, i.e., `'`

2021-06-25 06:42 UTC, nicnocquee approved these changes

2021-06-25 06:43 UTC, merged