fix: the sidebar can't be scroll
hyperjumptech/symon pull request #254
Opened 2021-06-28 10:19 UTC by kevinhermawan

# Symon Pull Request (PR)

Fixes #252

2021-06-29 02:30 UTC, dennypradipta requested changes

2021-06-29 02:30 UTC, dennypradipta commented on src/client/components/layout/index.tsx
> +        <div className="container-content container mx-auto px-4 py-5 sm:px-6 lg:px-7">
If there is no changes/addition for "container-content" class, kindly remove it as I don't see any additional CSS rule was made

2021-06-29 02:33 UTC, dennypradipta commented on src/client/components/layout/index.tsx
> +        <div className="container-content container mx-auto px-4 py-5 sm:px-6 lg:px-7">
Unless if you want to explain the div is the place where "container content" supposed to be, use id instead

2021-06-29 08:09 UTC, gsukanto approved these changes

2021-06-30 02:15 UTC, kevinhermawan commented on src/client/components/layout/index.tsx
> +        <div className="container-content container mx-auto px-4 py-5 sm:px-6 lg:px-7">
Oh yeah, I'll remove `container-content`.

2021-06-30 02:21 UTC, dennypradipta approved these changes

2021-06-30 02:22 UTC, merged